service: env-compare-rest
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 1536
plugins:
  - serverless-dotenv-plugin
  - serverless-aws-function-url-custom-domain
  - serverless-wsgi
  - serverless-python-requirements
custom:
  wsgi:
    app: app.app
    packRequirements: false
  urlDomain:
    apiDomain: ${env:API_DOMAIN}
    hostedZoneName: ${env:HOSTED_ZONE_NAME}
    certificateArn: ${env:CERTIFICATE_ARN}
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    url: true
    timeout: 15

package:
  patterns:
    - '!node_modules/**'
    - '!venv/**'
    - '!.github/**'
