name: Deploy on dev server

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: ftapiat/env-compare-sls-deploy-action@v1.0.4
        with:
          env-file: ${{ secrets.ENV_FILE }}
          node-version: ${{ matrix.node-version }}
          sls-stage: ${{ vars.SLS_STAGE }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
