name: Deploy on dev server

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: ftapiat/env-compare-sls-deploy-action@v1
